apiVersion: apps/v1
kind: Deployment
metadata:
  name: indicadores-service
spec:
  replicas: {{ .Values.indicadoresService.replicaCount }}
  selector:
    matchLabels: { app: indicadores-service }
  template:
    metadata:
      labels: { app: indicadores-service }
    spec:
      containers:
        - name: indicadores-service
          image: "{{ .Values.indicadoresService.image.repository }}:{{ .Values.indicadoresService.image.tag }}"
          ports:
            - containerPort: {{ .Values.indicadoresService.port }}
          envFrom:
            - configMapRef: { name: solicitudes-platform-config }
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef: { name: {{ .Values.secrets.dbPasswordSecretName }}, key: password }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: {{ .Values.indicadoresService.port }} }
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: {{ .Values.indicadoresService.port }} }
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            {{- toYaml .Values.indicadoresService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: indicadores-service
spec:
  selector: { app: indicadores-service }
  ports:
    - port: {{ .Values.indicadoresService.port }}
      targetPort: {{ .Values.indicadoresService.port }}
